version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_USER_PASSWORD=root
    networks:
        - node-network

  app:
    build:
      context: nodejs
    container_name: app
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh node index.js
    networks:
      - node-network
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge