name: ci-goapp-workflow
on:
  pull_request:
    branches:
      - develop
    paths:
      - 'integracao-continua/goapp/**'
  push:
    branches:
      - develop
    paths:
      - 'integracao-continua/goapp/**'
defaults:
  run:
    working-directory: ./integracao-continua/goapp
strategy:
  matrix:
    go: ['1.14', '1.15']
jobs:
  check-goapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go
